#!/bin/bash
set -e
# Color Palette - Next Gen Theme
RESET="\e[0m"
BOLD="\e[1m"
DIM="\e[2m"
UNDERLINE="\e[4m"
# Primary Colors
CYAN="\e[96m"
BLUE="\e[94m"
PURPLE="\e[95m"
GREEN="\e[92m"
YELLOW="\e[93m"
RED="\e[91m"
WHITE="\e[97m"
# Accents
NEON_GREEN="\e[38;5;82m"
NEON_PURPLE="\e[38;5;165m"
NEON_BLUE="\e[38;5;75m"
GLOW="\e[38;5;51m"
DANGER="\e[38;5;196m"

clear
    cat << "EOF"
██╗██╗██╗  ██╗ ██████╗ ███████╗██╗   ██╗ ██ ██████████
     ██║██║██║ ██╔╝██╔═══██╗╚══███╔╝╚██╗ ██╔╝ ╚ ██
     ██║██║█████╔╝ ██║   ██║  ███╔╝  ╚████╔╝     ██║   
██   ██║██║██╔═██╗ ██║   ██║ ███╔╝    ╚██╔╝      ██║   
╚█████╔╝██║██║  ██╗╚██████╔╝███████╗  ██║       ██
 ╚════╝ ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝  ╚═╝       ╚═╝

echo ""
echo " 1) Install Panel"
echo " 2) Install Wings"
echo " 3) Install Cloudflare"
echo " 3) EXIT"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1) run_remote_script "https://raw.githubusercontent.com/jikoz/codes/refs/heads/main/script" "Install Panel
    ;;
  2)
    clear
    cat << "EOF"
██╗██╗██╗  ██╗ ██████╗ ███████╗██╗   ██╗ ██ ██████████
     ██║██║██║ ██╔╝██╔═══██╗╚══███╔╝╚██╗ ██╔╝ ╚ ██
     ██║██║█████╔╝ ██║   ██║  ███╔╝  ╚████╔╝     ██║   
██   ██║██║██╔═██╗ ██║   ██║ ███╔╝    ╚██╔╝      ██║   
╚█████╔╝██║██║  ██╗╚██████╔╝███████╗  ██║       ██
 ╚════╝ ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝  ╚═╝       ╚═╝
EOF
  
    ;;
  3)
   clear
    cat << "EOF"
██╗██╗██╗  ██╗ ██████╗ ███████╗██╗   ██╗ ██ ██████████
     ██║██║██║ ██╔╝██╔═══██╗╚══███╔╝╚██╗ ██╔╝ ╚ ██
     ██║██║█████╔╝ ██║   ██║  ███╔╝  ╚████╔╝     ██║   
██   ██║██║██╔═██╗ ██║   ██║ ███╔╝    ╚██╔╝      ██║   
╚█████╔╝██║██║  ██╗╚██████╔╝███████╗  ██║       ██
 ╚════╝ ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝  ╚═╝       ╚═╝
EOF

    ;;
  4)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
