#!/bin/bash
set -e
# Color Palette - Next Gen Theme
RESET="\e[0m"
BOLD="\e[1m"
DIM="\e[2m"
UNDERLINE="\e[4m"
# Primary Colors
CYAN="\e[96m"
BLUE="\e[94m"
PURPLE="\e[95m"
GREEN="\e[92m"
YELLOW="\e[93m"
RED="\e[91m"
WHITE="\e[97m"
# Accents
NEON_GREEN="\e[38;5;82m"
NEON_PURPLE="\e[38;5;165m"
NEON_BLUE="\e[38;5;75m"
GLOW="\e[38;5;51m"
DANGER="\e[38;5;196m"

clear
    cat << "EOF"
██╗██╗██╗  ██╗ ██████╗ ███████╗██╗   ██╗ ██ ██████████
     ██║██║██║ ██╔╝██╔═══██╗╚══███╔╝╚██╗ ██╔╝ ╚ ██
     ██║██║█████╔╝ ██║   ██║  ███╔╝  ╚████╔╝     ██║   
██   ██║██║██╔═██╗ ██║   ██║ ███╔╝    ╚██╔╝      ██║   
╚█████╔╝██║██║  ██╗╚██████╔╝███████╗  ██║       ██
 ╚════╝ ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝  ╚═╝       ╚═╝

EOF

echo ""
echo "${BLUE}${BOLD} 1) Install Panel"
echo "${GREEN}${BOLD} 2) Install Wings"
echo "${RED}${BOLD} 3) Soon"
echo "${YELLOW}${BOLD} 4) EXIT"
echo ""
read -p "Select option [1-3]: " opt

case $opt in
  1)
    clear
    cat << "EOF"
██╗██╗██╗  ██╗ ██████╗ ███████╗██╗   ██╗████████╗
     ██║██║██║ ██╔╝██╔═══██╗╚══███╔╝╚██╗ ██╔╝╚══██╔══╝
     ██║██║█████╔╝ ██║   ██║  ███╔╝  ╚████╔╝    ██║   
██   ██║██║██╔═██╗ ██║   ██║ ███╔╝    ╚██╔╝     ██║   
╚█████╔╝██║██║  ██╗╚██████╔╝███████╗   ██║      ██║   
 ╚════╝ ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝   ╚═╝      ╚═╝
EOF

   bash <(curl -s https://raw.githubusercontent.com/jikoz/codes/refs/heads/main/script)
   ;;
  2)
    
    ;;
  3)
    echo "SOON"
    exit 0
    ;;
  4)
    exit 0
    ;;
  *)
    echo "❌ Invalid Option"
    sleep 1
    ;;
esac
done
